name: deploy

on:
  push:
    tags: [latest]
    branches:
      - main

jobs:
  deploy:
    name: Deploy to R2
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug Directory
        run: |
          echo "Directory: $(pwd)" && echo "Contents: $(ls -la)" && echo "Dist: $(ls -la dist)"

      - name: Upload to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.REGION }}
          S3_URI: ${{ secrets.S3_URI }}
        run: |
          AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION=$AWS_REGION aws s3 sync dist/ $S3_URI --endpoint-url https://$CLOUDFLARE_ACCOUNT_ID.r2.cloudflarestorage.com/ --size-only --only-show-errors --exact-timestamps --delete
